### ISSUE TITLE
Switch to using ShellCheck from containers

### ISSUE THREAD

**Issue by zhao-lin-li** [zhao-lin-li/project_template_with_containers#1]
With RHEL8/ubi8, it is easier to just use ShellCheck from within a stand-alone container, similar to how running end-to-end tests is easier to use a separate cypress container.

**Comment by zhao-li** [comment]
reference this: https://gitlab.com/starting-spark/porter/backend/-/blob/master/scripts/lint_app/run_shellcheck.sh
